name: Linter

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Trunk
        run: npm install -g trunk
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: trunk check
